# Generated by Django 5.0.7 on 2024-07-19 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='access_key',
            name='key_id',
        ),
    ]
